### ISSUE TITLE
NoneType issues when using DNS file

### ISSUE THREAD

**Issue by theabraxas** [mschwager/fierce#16]
Here are the raw errors with '...' denoting omitted info:

abraxas@AttackVM:~/recon/fierce$ python3 fierce.py --domain cnn.com --subdomain-file default.txt
.....

```
Found: access.cnn.com. (64.20.247.69)
Nearby:
{'64.20.247.64': 'mail3.access.cnn.com.'}
Found: alerts.cnn.com. (151.101.24.73)
Found: asia.cnn.com. (157.166.249.13)
Found: at.cnn.com. (157.166.226.26)
Nearby:
{'157.166.226.22': 'io.cnn.net.',
...
}
Traceback (most recent call last):
  File "fierce.py", line 301, in <module>
    main()
  File "fierce.py", line 298, in main
    fierce(**vars(args))
  File "fierce.py", line 223, in fierce
    ip = ipaddress.IPv4Address(record[0].address)
  File "/home/abraxas/.local/lib/python3.5/site-packages/dns/resolver.py", line 192, in __getitem__
    return self.rrset[i]
TypeError: 'NoneType' object is not subscriptable
```

Another example:

```
abraxas@AttackVM:~/recon/fierce$ python3 fierce.py --domain .... --subdomain-file default.txt
SOA: ns0.dnsmadeeasy.com. (208.94.148.2)
Zone: failure
Wildcard: failure
Found: backup.....com. 
Nearby:
Traceback (most recent call last):
  File "fierce.py", line 301, in <module>
    main()
  File "fierce.py", line 298, in main
    fierce(**vars(args))
  File "fierce.py", line 246, in fierce
    find_nearby(resolver, ips, filter_func=filter_func)
  File "fierce.py", line 162, in find_nearby
    pprint.pprint({k: v[0].to_text() for k, v in reversed_ips.items() if v})
  File "fierce.py", line 162, in <dictcomp>
    pprint.pprint({k: v[0].to_text() for k, v in reversed_ips.items() if v})
  File "/home/abraxas/.local/lib/python3.5/site-packages/dns/resolver.py", line 186, in __len__
    return len(self.rrset)
TypeError: object of type 'NoneType' has no len()
```

I cannot get any scans using the files to finish.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
This is due to a CNAME record response without a corresponding A record. You can recreate it like so:

$ python3 fierce.py --domain keypr.com --subdomains outgoing

And you will see something like:

"""
NS: ns-1101.awsdns-09.org. ns-1979.awsdns-55.co.uk. ns-347.awsdns-43.com. ns-731.awsdns-27.net.
SOA: ns-347.awsdns-43.com. (205.251.193.91)
Zone: failure
Wildcard: failure
Traceback (most recent call last):
  File "fierce.py", line 408, in <module>
    main()
  File "fierce.py", line 405, in main
    fierce(**vars(args))
  File "fierce.py", line 290, in fierce
    ip = ipaddress.IPv4Address(record[0].address)
  File "../dnspython-1.15.0-py3.5.egg/dns/resolver.py", line 281, in __getitem__
TypeError: 'NoneType' object is not subscriptable
"""

See dig output:

"""
$ dig outgoing.keypr.com

; <<>> DiG ... <<>> outgoing.keypr.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: ...
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outgoing.keypr.com.		IN	A

;; ANSWER SECTION:
outgoing.keypr.com.	299	IN	CNAME	u4122848.wl099.sendgrid.net.

;; AUTHORITY SECTION:
wl099.sendgrid.net.	179	IN	SOA	ns10.dnsmadeeasy.com. dns.dnsmadeeasy.com. 2009017173 43200 3600 1209600 180

;; Query time: 65 msec
;; SERVER: 2001:4860:4860::8844#53(2001:4860:4860::8844)
;; WHEN: ...
;; MSG SIZE  rcvd: 145
"""

**Comment by 9Yg1rxeSeha90ZU1** [comment]
And here is a patch to resolve it:

--- fierce.py.orig	2017-01-03 22:23:35.948000000 -0500
+++ fierce.py	2017-01-03 22:22:51.056000000 -0500
@@ -286,8 +286,10 @@
 
         if record is None:
             continue
-
-        ip = ipaddress.IPv4Address(record[0].address)
+        try:
+            ip = ipaddress.IPv4Address(record[0].address)
+        except TypeError:
+            continue
         print("Found: {} ({})".format(url, ip))
 
         if kwargs.get('connect') and not ip.is_private:

**Comment by mschwager** [comment]
@9Yg1rxeSeha90ZU1 thanks for the reproducible error case!
